[package]
name = "regexpr-binding"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true

[build-dependencies]
cc.workspace = true
bindgen.workspace = true

[dependencies]
once_cell.workspace = true