[package]
name = "moor"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
antlr-rust = {git = "https://github.com/rrevenantt/antlr4rust"}
lazy_static = "1.4.0"
anyhow = "1.0.66"
thiserror = "1.0.37"
symbol_table = "0.3.0"
int-enum = "0.5.0"
text_io = "0.1.12"
paste = "1.0.9"
enumset = "1.0.12"
enumset_derive = "0.6.1"
serde = { version = "1.0.147", features = ["derive"] }
bincode = { version = "2.0.0-rc.2", features = ["serde"] }
bincode_derive = "2.0.0-rc.2"
serde_derive = "1.0.147"
rusqlite = { version = "*", features = ["bundled"] }
sea-query = "0.28.3"
sea-query-rusqlite = "0.2.0"
bytes = "1.2.1"
itertools = "0.10.5"
bytecheck = "0.7.0"
decorum = "0.3.1"
num-traits = "0.2.15"
snailquote = "0.3.1"
clap = "4.0.29"
clap_derive = "4.0.21"
slotmap = "1.0.6"
tokio = "1.27.0"
tokio-test = "0.4.2"