[package]
name = "moor"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
antlr-rust = {git = "https://github.com/rrevenantt/antlr4rust"}
lazy_static = "1.4.0"
anyhow = "1.0.66"
symbol_table = "0.3.0"
int-enum = "0.5.0"
text_io = "0.1.12"
paste = "1.0.9"
enumset = "1.0.12"
enumset_derive = "0.6.1"
bincode = "2.0.0-rc.2"
cyclebox = { git = "https://github.com/rdaum/the-cyclebox.git" }
rusqlite = { version = "0.28.0", features = ["bundled"] }
sea-query = "0.27.2"
sea-query-rusqlite = "0.1.0"