[package]
name = "moor"
version = "0.1.0"
edition = "2021"

[dependencies]
lazy_static = "1.4.0"
anyhow = "1.0.66"
thiserror = "1.0.37"
int-enum = "0.5.0"
text_io = "0.1.12"
paste = "1.0.12"
bytes = "1.2.1"
itertools = "0.10.5"
bytecheck = "*"
decorum = "0.3.1"
num-traits = "0.2.15"
snailquote = "0.3.1"
clap = "4.0.29"
clap_derive = "4.0.21"
dashmap = "5.4.0"
rand = "0.8.5"

tokio = { version = "1.27.0", features = ["full"] }
tokio-test = "0.4.2"
tungstenite = "*"
tokio-tungstenite = "*"

libc = "0.2.140"
hybrid-lock = "0.1.0"
rkyv = { version = "0.7.41", features = ["validation"] }
repr-trait = "1.0.0"
enum-primitive-derive = "0.2.2"
futures-util = "0.3.28"
async-trait = "0.1.68"
pest = "2.5.7"
pest_derive = "2.5.7"

tracing = "0.1.29"
tracing-subscriber = "0.3"

fast-counter = "1.0.0"

magic-crypt = "3.1.12"
md5 = "0.7.0"