[workspace]
resolver = "2"

members = [
  "crates/values",
  "crates/kernel",
  "crates/rpc-common",
  "crates/daemon",
  "crates/host",
  "crates/server",
  "crates/regexpr-binding",
]

[workspace.package]
edition = "2021"
repository = "https://github.com/rdaum/moor.git"
license = "Apache-2.0"

[workspace.dependencies]
## Command line arguments parsing.
clap = "4.3.19"
clap_derive = "4.3.12"

#
futures = "0.3.28"
futures-util = { version = "0.3.28", features = ["sink", "std"] }
async-trait = "0.1.73"
tower-http = { version = "0.4.3", features = ["add-extension", "auth", "compression-full", "trace"] }

## HTTP/websockets front-end
axum = { version = "0.6.19", features = ["ws", "headers"] }
serde_json = "1.0.104"
serde = "1.0.178"

## Asynchronous transaction processing & networking
tokio = { version = "1.29.1", features = ["full"] }
tokio-test = "0.4.2"
tokio-util = { version = "0.7.8",  features = ["full"] }

tungstenite = "0.20.0"           # Websockets
tokio-tungstenite = "0.20.0"

tmq = "0.4.0"

## Logging & tracing
tracing = "0.1.37"
tracing-test = "0.2.4"
tracing-subscriber = "0.3.17"
tracing-chrome = "0.7.1"
metrics-exporter-prometheus = "0.12.1"
metrics = "0.21.1"
metrics-util = { version = "0.15.1",  default-features = false, features = ["recency", "registry", "summary"] }
metrics-macros = "0.7.0"

binary-layout = "3.1.3"
bytes = "1.4.0"
chrono = "0.4.26"
decorum = "0.3.1"  # For ordering & comparing our floats
enum-primitive-derive = "0.2.2"
inventory = "0.3.12"
itertools = "0.11.0"
lazy_static = "1.4.0"
num-traits = "0.2.16"
once_cell = "1.17.2"
rustyline = "12.0.0"
strum = { version = "0.25.0", features = ["derive"] }
text_io = "0.1.12" # Used for reading text dumps.
uuid = { version = "1.4.1", features = ["v4"] }
yoke = "0.7.1"
dashmap = "5.5.0"

## Required for MOO builtins.
pwhash = "1.0.0" # For MOO's hokey "crypt" function, which is unix's crypt(3) basically
md5 = "0.7.0" # For MOO's "string_hash"
rand = "0.8.5"

## Compiler grammar/parser
pest = "2.7.1"
pest_derive = "2.7.1"

## Error declaration/ handling
anyhow = { version = "1.0.75", features = ["backtrace"] }
thiserror = "1.0.47"

## For macro-ing
paste = "1.0.12"

# For the DB layer.
rocksdb = "0.21.0"
crossbeam-channel = "0.5.8"
bincode = "2.0.0-rc.3"

# Dev dependencies
tempfile = "3.8.0"

# Bindings
cc = { version = "1.0", features = ["parallel"] }
bindgen = "0.66.1"

# testing
test-case = "3.1.0"
unindent = "0.2.2"
pretty_assertions = "1.4.0"
