version: "3.9"
services:
  moor:
    build: .
    container_name: "moor-dev"
    volumes:
      - ./.cargo/registry:/usr/local/cargo/registry:cached
      - ./.target:/root/target:cached
      - .:/moor:cached
    environment:
      - CARGO_TARGET_DIR=/root/target
    command: sh -c "cargo watch -w Cargo.toml -w src -x 'run --release -- out.db JHCore-DEV-2.db 0.0.0.0:8080'"
    ports:
      - "8080:8080"


