# Docker composition for starting up the Moor system in cargo-watch mode, running with separate `daemon` and `host`
# binaries (communicating via ZMQ RPC), with VictoriaMetrics and VMagent for metrics collection, and Grafana for
# visualization.

# The first time the image starts, it will import JHCORE-DEV-2.db from the root of the repository. This is a recent
# JaysHouseCore database, with no modifications. After import, `development.db` will contain the (RocksDb) database
# that resulted. To re-import the textdump, simply delete this directory.

# This composition is not intended for production use, but for development and testing, but could be used as a template
# production once we're in a better place.

# After this is running, a MUD client or telnet client can connect to port 8888 on localhost to interact with the
# system. (e.g. telnet localhost 8888)

# Grafana will be available at http://localhost:3000/ password is admin/admin
# victoriametrics will be available at http://localhost:8428/

version: "3.9"
volumes:
  vmagentdata: {}
  vmdata: {}
  grafanadata: {}
networks:
  moor_net:
services:
  moor-daemon:
    build: ./
    container_name: "moor-daemon"
    volumes:
      - ./.cargo/registry:/usr/local/cargo/registry:cached
      - ./.target:/root/target:cached
      - ./:/moor:cached
    environment:
      - CARGO_TARGET_DIR=/root/target
    working_dir: /moor
    command: >
        sh -c "RUST_BACKTRACE=1 cargo watch -w crates/kernel -w crates/rpc-common -w crates/daemon -w crates/values -x 
        'run -p moor-daemon -- development.db --textdump=JHCore-DEV-2.db'"
    ports:
      # ZMQ ports
      - "7899:7899"
      - "7898:7898"
      # HTTP port for prometheus endpoint for metrics export
      - "9000:9000"
    networks:
      - moor_net
  moor-host:
    build: ./
    container_name: "moor-host"
    volumes:
      - ./.cargo/registry:/usr/local/cargo/registry:cached
      - ./.target:/root/target:cached
      - ./:/moor:cached
    environment:
      - CARGO_TARGET_DIR=/root/target
    working_dir: /moor
    command: >
      sh -c "RUST_BACKTRACE=1 cargo watch -w crates/rpc-common -w crates/host -w crates/values -x 
      'run -p moor-host -- --telnet-address=0.0.0.0:8888 --rpc-server=tcp://moor-daemon:7899 --narrative-server=tcp://moor-daemon:7898'"
    ports:
      # Telnet listener
      - "8888:8888"
    networks:
      - moor_net
  vmagent:
    container_name: vmagent
    image: victoriametrics/vmagent:v1.92.1
    depends_on:
      - "victoriametrics"
    ports:
      - "8429:8429"
    volumes:
      - vmagentdata:/vmagentdata
      - ./deploy/vmagent:/etc/prometheus/
    command:
      - "--promscrape.config=/etc/prometheus/prometheus.yml"
      - "--remoteWrite.url=http://victoriametrics:8428/api/v1/write"
    networks:
      - moor_net
    restart: always
  victoriametrics:
    container_name: victoriametrics
    image: victoriametrics/victoria-metrics:v1.92.1
    ports:
      - "8428:8428"
    volumes:
      - vmdata:/storage
    command:
      - "--storageDataPath=/storage"
      - "--httpListenAddr=:8428"
    networks:
      - moor_net
    restart: always
  grafana:
    container_name: grafana
    image: grafana/grafana:10.0.3
    depends_on:
      - "victoriametrics"
    ports:
      - "3000:3000"
    volumes:
      - grafanadata:/var/lib/grafana
      - ./deploy/grafana/provisioning:/etc/grafana/provisioning/
      - ./deploy/grafana/dashboards:/var/lib/grafana/dashboards
    networks:
      - moor_net
    restart: always