[package]
name = "rpc-sync-client"
version = "0.1.0"
description = "Utilities for connection to the 0MQ RPC server via blocking synchronous calls"
edition.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
# Own
rpc-common = { path = "../rpc-common" }

bincode.workspace = true
tracing.workspace = true
uuid.workspace = true
zmq.workspace = true
