[package]
name = "moor-kernel"
version = "0.9.0-alpha"
authors.workspace = true
categories.workspace = true
edition.workspace = true
keywords.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
resolver = "2"
rust-version.workspace = true
description = "The actual implementation of most of the moor system; virtual machine, scheduler, and builtins."

[dev-dependencies]
moor-db = { path = "../db" }
tempfile.workspace = true

criterion.workspace = true
eyre.workspace = true
pretty_assertions.workspace = true
similar.workspace = true
similar-asserts.workspace = true
test-case.workspace = true
test_each_file.workspace = true
tracing.workspace = true

[[test]]
name = "regression-suite"
path = "testsuite/regression_suite.rs"

[[test]]
name = "moot-suite"
path = "testsuite/moot_suite.rs"

[[bench]]
name = "vm_benches"
harness = false

[dependencies]
## Own
moor-compiler = { path = "../compiler" }
moor-db = { path = "../db" }
moor-moot = { path = "../testing/moot" }
moor-values = { path = "../common" }

## General usefulness
bytes.workspace = true
chrono.workspace = true
crossbeam-channel.workspace = true
encoding_rs.workspace = true
lazy_static.workspace = true
libc.workspace = true
oneshot.workspace = true
semver.workspace = true
serde.workspace = true
strum.workspace = true
text_io.workspace = true
uuid.workspace = true

## Required for MOO builtins.
chrono-tz.workspace = true
iana-time-zone.workspace = true
md-5.workspace = true
onig.workspace = true
pwhash.workspace = true
rand.workspace = true
xml-rs.workspace = true

## Error declaration/ handling
thiserror.workspace = true

## For macro-ing
paste.workspace = true

## Logging & tracing
tracing.workspace = true

# For the DB layer.
bincode.workspace = true
