[package]
name = "moor-kernel"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true

[dev-dependencies]
tempfile.workspace = true
inventory.workspace = true
test-case.workspace = true
unindent.workspace = true
pretty_assertions.workspace = true

[[test]]
name = "basic-testsuite"
path = "testsuite/basic/basic_suite.rs"

[dependencies]

## Own
moor-values = { path = "../values" }
moor-compiler = { path = "../compiler" }
moor-db = { path = "../db" }

## General usefullness
itertools.workspace = true
lazy_static.workspace = true
async-trait.workspace = true
decorum.workspace = true
text_io.workspace = true
bytes.workspace = true
strum.workspace = true
uuid.workspace = true
chrono.workspace = true
sized-chunks.workspace = true

## Required for MOO builtins.
pwhash.workspace = true
md5.workspace = true
rand.workspace = true
onig.workspace = true
chrono-tz.workspace = true
iana-time-zone.workspace = true

## Error declaration/ handling
thiserror.workspace = true

## For macro-ing
paste.workspace = true

## Asynchrony and/or networking
tokio.workspace = true
tokio-test.workspace = true

## Logging & tracing
tracing.workspace = true
tracing-test.workspace = true
metrics.workspace = true
metrics-util.workspace = true
metrics-macros.workspace = true

# For the DB layer.
crossbeam-channel.workspace = true
bincode.workspace = true
