[package]
name = "moor-web-host"
version = "0.1.0"
description = "A RESTful web front end for interacting with the moor system"
edition.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
rust-version.workspace = true
categories.workspace = true
keywords.workspace = true
readme.workspace = true

[dependencies]
moor-values = { path = "../values" }
rpc-async-client = { path = "../rpc-async-client" }
rpc-common = { path = "../rpc-common" }

## Command line arguments parsing.
clap.workspace = true
clap_derive.workspace = true

# General.
color-eyre.workspace = true
eyre.workspace = true
futures-util.workspace = true
thiserror.workspace = true

## Asynchronous transaction processing & networking
tokio.workspace = true

## Logging & tracing
tracing-subscriber.workspace = true
tracing.workspace = true

## ZMQ / RPC
tmq.workspace = true
uuid.workspace = true

# HTTP/websockets layer
axum.workspace = true
serde.workspace = true
serde_derive.workspace = true
serde_json.workspace = true
