[package]
name = "moor-web-host"
version = "0.1.0"
edition.workspace = true
repository.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
moor-values = { path = "../values" }
rpc-common = { path = "../rpc-common" }

## Command line arguments parsing.
clap.workspace = true
clap_derive.workspace = true
strum.workspace = true

# General.
anyhow.workspace = true
async-trait.workspace = true
bincode.workspace = true
futures-util.workspace = true
futures.workspace = true
thiserror.workspace = true

## Asynchronous transaction processing & networking
tokio-util.workspace = true
tokio.workspace = true

## Logging & tracing
metrics-exporter-prometheus.workspace = true
metrics-macros.workspace = true
metrics-util.workspace = true
metrics.workspace = true
tracing-chrome.workspace = true
tracing-subscriber.workspace = true
tracing.workspace = true

## ZMQ / RPC
itertools.workspace = true
tmq.workspace = true
uuid.workspace = true

# HTTP/websockets layer
axum-extra.workspace = true
axum.workspace = true
serde.workspace = true
serde_derive.workspace = true
serde_json.workspace = true
