[package]
name = "rpc-common"
version = "0.1.0"
edition.workspace = true
repository.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
# Own
moor-values = { path = "../values" }

bincode.workspace = true
futures-util.workspace = true
thiserror.workspace = true
tmq.workspace = true
tracing.workspace = true
uuid.workspace = true
