[package]
name = "rpc-common"
version = "0.1.0"
description = "Common entities used for 0MQ based RPC communication with the daemon."
edition.workspace = true
repository.workspace = true
license.workspace = true
authors.workspace = true
rust-version.workspace = true

[dependencies]
# Own
moor-values = { path = "../values" }

bincode.workspace = true
thiserror.workspace = true
