[package]
name = "rpc-common"
version = "0.1.0"
edition.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
bincode.workspace = true
moor-values = { path = "../values" }
thiserror.workspace = true
tmq.workspace = true
uuid.workspace = true
anyhow.workspace = true
tracing.workspace = true
futures-util.workspace = true
