[package]
name = "moor-values"
version = "0.1.0"
authors.workspace = true
build = "build.rs"
categories.workspace = true
edition.workspace = true
keywords.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
rust-version.workspace = true
description = "The set of values, and model/entities used across the system"

[build-dependencies]
shadow-rs.workspace = true

[dependencies]
binary-layout.workspace = true
bincode.workspace = true
bytes.workspace = true
enum-primitive-derive.workspace = true
im.workspace = true
itertools.workspace = true
lazy_static.workspace = true
log = "0.4.25"
num-traits.workspace = true
paste.workspace = true
serde.workspace = true
shadow-rs.workspace = true
strum.workspace = true
thiserror.workspace = true
ustr.workspace = true
uuid.workspace = true
