[package]
name = "rpc-common"
version = "0.1.0"
authors.workspace = true
categories.workspace = true
edition.workspace = true
keywords.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
rust-version.workspace = true
description = "Common entities used for 0MQ based RPC communication with the daemon."

[dependencies]
# Own
moor-values = { path = "../../common" }

bincode.workspace = true
clap.workspace = true
clap_derive.workspace = true
thiserror.workspace = true

# Auth/Auth
pem.workspace = true
rusty_paseto.workspace = true
