[package]
name = "tuplebox"
version = "0.1.0"
edition = "2021"
description = "Simple MVCC binary relation storage"

[dependencies]
itertools = "0.10.5"
hybrid-lock = "0.1.0"
thiserror = "1.0.40"
anyhow = "1.0.70"
