[package]
name = "moor-daemon"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
rust-version.workspace = true

[dependencies]
moor-db = { path = "../db" }
moor-kernel = { path = "../kernel" }
moor-values = { path = "../values" }
rpc-common = { path = "../rpc-common" }

## Command line arguments parsing.
clap.workspace = true
clap_derive.workspace = true
strum.workspace = true

# General.
bincode.workspace = true
color-eyre.workspace = true
eyre.workspace = true

## Logging & tracing
tracing-subscriber.workspace = true
tracing.workspace = true

## RPC daemon support
serde.workspace = true
serde_json.workspace = true
uuid.workspace = true
zmq.workspace = true

# Auth/Auth
ed25519-dalek.workspace = true
pem.workspace = true
rand.workspace = true
rusty_paseto.workspace = true
