[package]
name = "moor-db"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true

[dev-dependencies]
tempfile.workspace = true

[dependencies]
## Own
moor-values = { path = "../values" }

## General usefullness
async-trait.workspace = true
strum.workspace = true
uuid.workspace = true

## Error declaration/ handling
thiserror.workspace = true

## Asynchrony and/or networking
tokio.workspace = true
tokio-test.workspace = true

## Logging & tracing
tracing.workspace = true
tracing-test.workspace = true
metrics.workspace = true
metrics-macros.workspace = true

# For the DB layer.
rocksdb.workspace = true
crossbeam-channel.workspace = true
bincode.workspace = true