[package]
name = "moor-db"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true

[[bench]]
name = "tb_single_thread"
harness = false

[dev-dependencies]
tempfile.workspace = true
rand.workspace = true
serde_json.workspace = true
serde.workspace = true
criterion.workspace = true

[dependencies]
## Own
moor-values = { path = "../values" }

## General usefullness
async-trait.workspace = true
strum.workspace = true
uuid.workspace = true
lazy_static.workspace = true
human_bytes.workspace = true

## Error declaration/ handling
thiserror.workspace = true

## Asynchrony and/or networking
tokio.workspace = true
tokio-test.workspace = true

## Logging & tracing
tracing.workspace = true
tracing-test.workspace = true
metrics.workspace = true
metrics-macros.workspace = true

# For the DB layer.
crossbeam-channel.workspace = true
bincode.workspace = true
im.workspace = true
sized-chunks.workspace = true
binary-layout.workspace = true
libc.workspace = true
atomic-wait.workspace = true
okaywal.workspace = true
io-uring.workspace = true
hi_sparse_bitset.workspace = true
tokio-eventfd.workspace = true
fast-counter.workspace = true

# For testing & benching common bits
serde_json.workspace = true
serde.workspace = true
