[package]
name = "moor-server"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
moor-kernel = { path = "../kernel" }
moor-values = { path = "../values" }

## Command line arguments parsing.
clap.workspace = true
clap_derive.workspace = true
strum.workspace = true

#
anyhow.workspace = true
futures.workspace = true
futures-util.workspace = true
async-trait.workspace = true
tower-http.workspace = true
dashmap.workspace = true

## Asynchronous transaction processing & networking
tokio.workspace = true
tokio-util.workspace = true

# HTTP/websockets layer
axum.workspace = true
serde_json.workspace = true
serde.workspace = true
serde_derive = "1.0.178"

tungstenite.workspace = true
tokio-tungstenite.workspace = true

## Logging & tracing
tracing.workspace = true
tracing-subscriber.workspace = true
tracing-chrome.workspace = true
metrics-exporter-prometheus.workspace = true
metrics.workspace = true
metrics-util.workspace = true
metrics-macros.workspace = true

## For Repl
rustyline.workspace = true
