name: Rust
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_default:

    runs-on: ubuntu-latest

    steps:
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: cmake python3-dev swig
          version: 1.0
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose

  build_all:

    runs-on: ubuntu-latest

    steps:
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: cmake python3-dev swig
          version: 1.0
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
      - name: Build
        run: cargo build --verbose --all-features --all-targets
      - name: Run tests
        run: cargo test --verbose --all-features --all-targets

  clippy_check:
    runs-on: ubuntu-latest
    steps:
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: cmake python3-dev swig
          version: 1.0
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
      - run: rustup component add clippy
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features
